// Copyright (c) 2025 Eric Larsen
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the “Software”), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
// IN THE SOFTWARE.
// ****************************************************************************
// ****************************************************************************
//
//
#include "instance.h"
#include <algorithm>

#ifndef __MODEL_H__
#define __MODEL_H__

using namespace std;

struct Model
{

    const Instance *inst;

    Model(const Instance *inst);

    // Modifies model to reflect scenario currently under test.
    virtual void modify() = 0;

    // Verifies if scenario is feasible.
    virtual bool testScenario() = 0;

    virtual ~Model() {};
};

#if CPLEX

#include <ilcplex/ilocplex.h>

// calls CPLEX macro
// (empty as of 29Aug2023 and placeholder
// for future developments)
ILOSTLBEGIN

typedef IloArray<IloNumVarArray> IloNumVarArray2;
typedef IloArray<IloRangeArray> IloRangeArray2;

// Handling verification of feasibility for each scenario generated by the
// Hoyland-Kaut-Wallace algorithm with the CPLEX solver.  (Assuming all arcs are open, checking for
// feasibility of second stage problem under current scenario.)
struct CPXModel : public Model
{
    IloEnv iloEnv;

    IloModel iloModel;

    IloCplex cplex;

    // 2-dimensional array of flow variables (first dim is arcs,
    // second dim is commodities)
    IloNumVarArray2 X_ak;

    // constraints restricting net flow on each node for each commodity
    IloRangeArray2 constr_flowCons;

    // constraints restricting total flow on each arc
    IloRangeArray constr_capArcs;

    IloExpr objExpr;

    CPXModel(const Instance *inst);

    ~CPXModel()
    {
        objExpr.end();
        cplex.end();
        iloModel.end();
        iloEnv.end();
    }

    // Sets up 2-dimensional array of flow variables.
    void createXVars();

    // Sets up constraints maintaining flow conservation at each node.
    void createConstrFlowCons();

    // Sets up constraints restricting total flow on each arc.
    void createConstrCapArcs();

    virtual bool testScenario();
};

// Subclass handling DOW and RSTD formats
struct CPXModel_DowRStd : public CPXModel
{
    CPXModel_DowRStd(const Instance *inst) : CPXModel(inst)
    {
    }
    virtual void modify();
};

// Subclass handling GSTD format
struct CPXModel_GStd : public CPXModel
{
    CPXModel_GStd(const Instance *inst) : CPXModel(inst)
    {
    }
    virtual void modify();
};

#elif HIGHS

#include "Highs.h"

// Handling verification of feasibility for each scenario generated by the
// Hoyland-Kaut-Wallace algorithm with the HiGHS solver.  (Assuming all arcs are open, checking for
// feasibility of second stage problem under current scenario.)

// see https://github.com/ERGO-Code/HiGHS/blob/master/examples/call_highs_from_cpp.cpp
struct HIGHSModel : Model
{

    HighsModel highsModel;

    Highs highs;

    HighsStatus return_status;

    int numbRows1;

    int numbRows2;

    int numbRows;

    int numbCols;

    // preliminary A matrix
    vector<vector<int>> prelAMatrix;

    void setUpperRows();

    void setLowerRows();

    HIGHSModel(const Instance *inst);

    ~HIGHSModel()
    {
        highs.clear();
        highsModel.clear();
    }

    void setHIGHSAMatrix();

    virtual bool testScenario();
};

// Subclass handling DOW and RSTD formats
struct HIGHSModel_DowRStd : public HIGHSModel
{
    HIGHSModel_DowRStd(const Instance *inst) : HIGHSModel(inst)
    {
    }
    virtual void modify();
};

// Subclass handling GSTD format
struct HIGHSModel_GStd : public HIGHSModel
{
    HIGHSModel_GStd(const Instance *inst) : HIGHSModel(inst)
    {
    }
    virtual void modify();
};

#endif

#endif
